# Generated by Django 2.0.5 on 2020-05-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='static/img/picture.png', upload_to='post_thumbnails'),
        ),
    ]
