# Generated by Django 2.0.5 on 2020-05-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='/post_thumbnails/picture.png', upload_to='post_thumbnails'),
        ),
    ]
