# Generated by Django 2.0.5 on 2020-05-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200507_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='media/post_thumbnails/picture.png', upload_to='post_thumbnails'),
        ),
    ]
