# Generated by Django 2.0.5 on 2020-05-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200507_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='media/post_thumbnails/picture.jpg', upload_to='post_thumbnails'),
        ),
    ]
