# Generated by Django 2.0.5 on 2020-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200508_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='post_thumbnails/picture.png', upload_to='post_thumbnails'),
        ),
    ]
