# Generated by Django 2.0.5 on 2020-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200508_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='picture.png', upload_to='post_thumbnails'),
        ),
    ]
